apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: flusdemo
  name: flusdemo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: flusdemo
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: flusdemo
    spec:
      containers:
      - image: nginx
        name: nginx
        resources: {}
status: {}
